version: '3.1'

volumes:
  crypto: {}

services:
  mongo:
    image: mongo
    container_name: crypto_mongo_server
    restart: on-failure
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=12345
    volumes:
      - ./migrations/:/docker-entrypoint-initdb.d/:ro
      - crypto:/data/db/

  mongo-express:
    image: mongo-express
    container_name: crypto_mongo_express
    restart: always
    ports:
      - 5000:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=12345
    depends_on:
      - mongo